### ISSUE TITLE
we'd like to contribute some extensions back, but can't even get the tests to run [JIRA: CLIENTS-43]

### ISSUE THREAD

**Issue by skaes** [basho/riak-ruby-client#145]
The README says

* Copy spec/support/test_server.yml.example to spec/support/test_server.yml and change that file according to your local installation of riak.

but there is no such file.

Could you please provide up to date instructions on how to get the tests running?

We have three extensions waiting in the queue:

* support for gzip encoded content via Content-Encoding
* support for client client side timeouts in the protobuf backend
* a bugfix for setting microseconds correctly for last_modfied timestamps

**Comment by Basho-JIRA** [comment]
[~Bryce], I'm guessing this can be closed. 

***[posted via JIRA by Derek Somogyi]***

**Comment by bkerley** [comment]
@skaes @boosty just following back up on this after being nudged today. Ruby clients ~> 2.0 (including the forthcoming 2.2 release), we've got some test documentation at http://basho.github.io/riak-ruby-client/rspecs.html#toc-configuring-for-running-tests . Ruby clients ~> 1.0 (including 1.4) are still supported, but we don't have any improvements or changes planned.

Closing the issue since I don't see anything actionable here; make a new issue or email me at bryce@basho.com if you still need help.
